[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'node_modules',
    'lib',
]
test = 'test/foundry'
cache_path  = 'forge-cache'

gas_reports = ["PaymentProcessor"]

optimizer = true
optimizer_runs = 600

[fuzz]
runs = 10000
max_test_rejects = 2560000

[invariant]
runs = 50
depth = 250
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config